export const register = [
  {
    type: "text",
    name: "gender",
    placeholder: "Gender",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "birthDate",
    placeholder: "Birthdate",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "height",
    placeholder: "Height",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "weight",
    placeholder: "Weight",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "eyeColor",
    placeholder: "Eye Color",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "hair",
    placeholder: "Hair",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "bloodGroup",
    placeholder: "Blood group",
    component: "p",
    className: "error",
  },
  {
    type: "email",
    name: "companyName",
    placeholder: "Company name",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "department",
    placeholder: "Department",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "title",
    placeholder: "Title",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "companyAddress",
    placeholder: "Company address",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "companyPostalCode",
    placeholder: "Postal code",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "companyCity",
    placeholder: "City",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "companyCountry",
    placeholder: "Country",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "iban",
    placeholder: "IBAN",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "number",
    placeholder: "Card number",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "type",
    placeholder: "Card type",
    component: "p",
    className: "error",
  },
  {
    type: "text",
    name: "expire",
    placeholder: "Card expire",
    component: "p",
    className: "error",
  },
];
