export const register = [
    {
      type: "text",
      name: "firstName",
      placeholder: "Firstname",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "lastName",
      placeholder: "Lastname",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "university",
      placeholder: "Education",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "address",
      placeholder: "Address",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "postalCode",
      placeholder: "PostalCode",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "city",
      placeholder: "City",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "country",
      placeholder: "Country",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "phone",
      placeholder: "Phone",
      component: "p",
      className: "error",
    },
    {
      type: "email",
      name: "email",
      placeholder: "E-mail",
      component: "p",
      className: "error",
    },
    {
      type: "text",
      name: "username",
      placeholder: "Username",
      component: "p",
      className: "error",
    },
    {
      type: "password",
      name: "password",
      placeholder: "Password",
      component: "p",
      className: "error",
    },
    {
      type: "password",
      name: "password2",
      placeholder: "Repeat the password",
      component: "p",
      className: "error",
    },
  ];